cluster-controller/image.yaml, kafka-base/image.yaml, kafka-connect-s2i/image.yaml, kafka-connect/image.yaml, kafka/image.yaml, templates/cluster-controller.yaml, templates/connect-s2i-template.yaml, templates/connect-template.yaml, templates/ephemeral-template.yaml, templates/persistent-template.yaml, templates/topic-controller.yaml, topic-controller/image.yaml, zookeeper/image.yaml
According to Cloud Enablement naming conventions,  the image family name should be prefixed with the vendor associated/responsible for it. In our case that would be "redhat".  
WDYT?
=> Update Image Name Vendor from jboss to redhat

operator/image.yaml
This PR fixes the boolean value for the label related to the appregistry. Without it, the build fails with:
```
[ppatiern@new-host-3 operator]$ cekit build
2019-06-17 09:16:06,447 cekit        INFO     Generating files for docker engine.
validation.invalid
--- All found errors ---
["Value 'True' is not of type 'str'. Path: '/value'"]
2019-06-17 09:16:06,459 cekit        ERROR    Cannot validate schema: Label
```
=> Fix boolean value in operator descriptor file

install/cluster-operator/050-Deployment-strimzi-cluster-operator.yaml, kafka/kafka-2.1.1/help.md, kafka/kafka-2.1.1/image.yaml, kafka/kafka-2.2.1/help.md, kafka/kafka-2.2.1/image.yaml, operator/modules/olm/manifests/amq-streams.v1.2.0.clusterserviceversion.yaml
Changes about new Kafka image names and fix for #106 as well.
=> Applied renaming for Kafka images removing the period in the version

bridge/image.yaml, kafka/kafka-2.1.1/image.yaml, kafka/kafka-2.2.1/image.yaml, operator/image.yaml
Images built and smoke tested. Cuts down the image size a little bit (~5MB) but meets the UBI7 requirement. We will be able to reduces the size of the images by removing unneeded dependencies added by cct_modules in future PRs
=> Migration to minimal Universal Base Image (ubi7-minimal)

bridge/image.yaml, kafka/kafka-2.1.1/image.yaml, kafka/kafka-2.2.1/image.yaml, kafka/modules/kafka/base/install.sh, operator/image.yaml
The installed cct_modules are adding a lot of unnecessary dependencies to our images e.g. openjdk-devel. By removing them we:
- Reduce the size of the images significantly ( ~100 MB )
- Reduce the the dependencies and CVE surface
- Reduce the complexity of image maintenance
=> Remove cct modules dependency

install/cluster-operator/021-ClusterRole-strimzi-cluster-operator-role.yaml, operator/modules/olm/manifests/1.3.0/amq-streams.v1.3.0.clusterserviceversion.yaml
We need to have a `watch` RBAC right for deleting non-namespaced objects such as CRBs and CRs.
=> Add watch RBAC for CRBs and CRs

bridge/modules/bridge/module.yaml, kafka/modules/kafka/2.2.1/install.sh, kafka/modules/kafka/2.2.1/module.yaml, kafka/modules/kafka/2.3.0/install.sh, kafka/modules/kafka/2.3.0/module.yaml, kafka/modules/kafka/base/install.sh, kafka/modules/kafka/base/module.yaml, kafka/modules/kafka/base/scripts/kafka_connect_run.sh, kafka/modules/kafka/base/scripts/kafka_mirror_maker_run.sh, kafka/modules/kafka/base/scripts/kafka_run.sh, operator/modules/operator/module.yaml
Kafka and all of its dependencies are now provided to us in a single zip file. With this zip file, we only need to unpack its contents into ${KAFKA_HOME} directory and not worry about downloading and installing Kafka and all of its dependencies separately.
I have also updated some of the Kafka run scripts here and upstream to be able to handle jar names with versioned suffixes.
=> Script updates for RC1

kafka/modules/kafka/2.2.1/install.sh, kafka/modules/kafka/2.2.1/module.yaml, kafka/modules/kafka/2.3.0/install.sh, kafka/modules/kafka/2.3.0/module.yaml
Changing the kafka.jar name used in the kafka-2.2.1 image and the kafka-2.3.0 image to "kafka-22.jar" and "kafka-23.jar" respectively so that CPaaS can differentiate between the jars in the CPaaS configuration files
=> Change kafka.jar names to enable CPaaS processing

bridge/modules/bridge/install.sh, bridge/modules/bridge/module.yaml
There is an extra root directory, "kafka-bridge-0.14.0.temporary-redhat-00012", included in the productized bridge zip (the other productized zips for strimzi do not have this extra directory, e.g. cluster-operator, user-operator, etc.). I have added some extra scripts to get around this, but we should probably remove this extra root directory in bridge zip at some point to follow the pattern of the other zip files
=> Change bridge artifact packaging to zip

operator-metadata/image.yaml
Talking with the operator pipeline people a couple weeks ago where they said we are supposed to be using the *prod* dist-git branch while reserving the other branches for some future RCM workflow for handling multistream operator releases
No rush on this PR as it shouldn't matter which dist-git branch we build off of right now
=> Update metadata image dist-git repo branch

common/modules/olm/manifests/1.4.0/amq-streams.v1.4.0.clusterserviceversion.yaml, common/modules/olm/manifests/1.4.1/amq-streams.v1.4.1.clusterserviceversion.yaml
When populating the SHAs for the 1.4.0 OLM files, I used the:
- incorrect brew builds
- incorrect field names for the `relatedImages` section
These files have now been corrected and verified by QE!
=> Fixing SHAs and typos in OLM files

common/modules/olm/manifests/amq-streams.v1.5.0.clusterserviceversion.yaml
Fixing the field name in the `relatedImages` section of the OLM files. 
Have been tested and verified by QE!
=> Fix typo in OLM files

bridge/modules/bridge/install.sh, operator-metadata/dist-git-files/container.yaml, operator/modules/operator/install.sh
This PR:
- Adds a new manifest configuration that is now required to run builds in OSBS
- Fixes tar user issue that was preventing images to be built locally with podman. More information can be found here [1]
[1] https://github.com/habitat-sh/builder/issues/365#issuecomment-382862233
=> Add manifest config + fix podman build issue

kafka/modules/kafka/base/install.sh, operator/modules/operator/install.sh
This trivial PR adds a temporaty patch for removing "tini" usage on the packaged scripts until "tini" will be available to be installed as rpm.
=> Remove "tini" patch

common/modules/olm/manifests/1.4.1/amq-streams.v1.4.1.clusterserviceversion.yaml
Only the Kafka images had this package installed and were affected by this vulnerability.
=> Update SHAs for bind-utils CVE respin

operator-metadata/dist-git-files/container.yaml
Backporting container.yaml changes to amqstreams14-dev branch
=> Update container.yaml with required flags

kafka/kafka-2.4.0/image.yaml, kafka/kafka-2.5.0/image.yaml, kafka/modules/kafka/base/install.sh, operator/image.yaml, operator/modules/operator/install.sh
The productized `tini` package version 0.18.0 has finally been released into the `amq-streams-1-for-rhel-7-server-rpms` repo so we can now start using it with our images!
Tested the changes on OpenShift and everything works great!
=> Adding tini package

bridge/image.yaml, kafka/kafka-2.4.0/image.yaml, kafka/kafka-2.5.0/image.yaml, operator/image.yaml
These repos are used by the UBI base image and new CVP policy requires us to list them in our content_sets.yml
=> Update content_sets.yml with rpm repos used by UBI base image

common/modules/olm/manifests/1.5.0/amq-streams.v1.5.0.clusterserviceversion.yaml, common/modules/olm/manifests/1.5.1/amq-streams.v1.5.1.clusterserviceversion.yaml, common/modules/olm/manifests/1.5.2/amq-streams.v1.5.2.clusterserviceversion.yaml, common/modules/olm/manifests/1.5.3/amq-streams.v1.5.3.clusterserviceversion.yaml
This resolves issue: https://github.com/jboss-container-images/amqstreams-1-openshift-image/issues/227
I can cherry-pick these fixes to the amqstreams15-dev branch afterwards in case there is another CVE crops up for 1.5.0
=> Fix typo Kafka Cannect to Kafka Connect

operator-metadata/manifests/amq-streams.package.yaml
I accidentally included this file from the old format when migrating the files for the bundle format. This PR removes that unnecessary file. I'll cherry-pick the change to 16-dev branch
=> Remove amq-streams.package.yaml file from old package manifest format

bridge/image.yaml, kafka/kafka-2.4.0/image.yaml, kafka/kafka-2.5.0/image.yaml, operator/image.yaml
Resolves #216 #217 and  #235
- Updates images to use Java 11
- Uses Java 11 package containing requested JVM debugging tools
- Installs other requested packages like `net-tools` and `lsof` for debugging
Note Kafka image descriptors already have `net-tools` RPM listed for install
=> Upgrade to Java 11 and add debugging tools

kafka/modules/kafka/base/stunnel-scripts/entity_operator_stunnel_config_generator.sh, kafka/modules/kafka/base/stunnel-scripts/kafka_stunnel_config_generator.sh
Enable all TLS protocol versions in the Kafka and EO sidecars to make them work smoothly after the 1.5 upgrade.
=> Enable all TLS versions in Kafka and EO sidecars

bridge/modules/bridge/module.yaml, kafka/kafka-2.6.0/image.yaml, kafka/modules/kafka/2.5.0/module.yaml, kafka/modules/kafka/2.6.0/install.sh, kafka/modules/kafka/2.6.0/module.yaml, kafka/modules/kafka/base/module.yaml, operator/modules/operator/module.yaml
The Cluster Operator jar needs to be rebuilt with an updated ` kafka-versions.yaml `file so it does not include Kafka 2.5.1. Once it is rebuilt I will update this PR with the appropriate MD5s and take it out of draft mode
CC @ppatierno (Hold off on the review until we update the Cluster Operator fixes!)
=> Update MD5s for AMQ Streams 1.6.0 CR1

examples/cruise-control/kafka-cruise-control.yaml, examples/kafka/kafka-ephemeral-single.yaml, examples/kafka/kafka-ephemeral.yaml, examples/kafka/kafka-jbod.yaml, examples/kafka/kafka-persistent-single.yaml, examples/kafka/kafka-persistent.yaml, examples/metrics/jmxtrans/jmxtrans.yaml, examples/metrics/kafka-cruise-control-metrics.yaml, examples/metrics/kafka-metrics.yaml, examples/mirror-maker/kafka-source.yaml, examples/mirror-maker/kafka-target.yaml, examples/security/scram-sha-512-auth/kafka.yaml, examples/security/tls-auth/kafka.yaml, examples/templates/cluster-operator/ephemeral-template.yaml, examples/templates/cluster-operator/persistent-template.yaml, operator-metadata/manifests/amq-streams.v1.6.0.clusterserviceversion.yaml
Thsi Pr adds the `inter.broker.protocol.version` to our examples to have it fixed there.
=> Add the inter.broker.protocol.version to our examples

bridge/image.yaml, kafka/kafka-2.5.0/image.yaml, kafka/kafka-2.6.0/image.yaml, operator/image.yaml
TL;DR CVP is adding a new requirements which require an update to our content_sets:
1) An RPM we install cannot be provided from more than one repo in our content_sets
2) We must list exact content_sets of our base image in our content_sets
We violated (1) since the `java-11-openjdk-devel` package was moved to the `rhel-7-server-rpms` repo. The `java-11-openjdk-devel` packaged is now provided by both the `rhel-7-server-rpms` and `rhel-7-server-optional-rpms` repos. To remedy this, we remove the `rhel-7-server-optional-rpms` repo which was added explicitly for the `java-11-openjdk-devel` package.
We violated (2) since we used `rhel-7-desktop-extras-rpms` instead of `rhel-7-server-extras-rpms`. Both repos provide the needed RPMs, but we must match the repos used by the base image.
Added …
=> Update content_sets to meet new CVP requirements

operator-metadata/image.yaml
The backport label `com.redhat.delivery.backport` causes the bundle to be backported to all OCP version <= 4.6.
Although we don't want this bundle backported to OCP versions < 4.5 we must do so if we want to support OLM install on OCP 4.5.
Reverting change back to set `com.redhat.delivery.backport` to `true`
=> Revert backport flag to true, which is necessary for OCP 4.5

operator-metadata/image.yaml
Resolves https://github.com/jboss-container-images/amqstreams-1-openshift-image/issues/263
=> Drop support for legacy app registry of OCP v4.5

bridge/image.yaml, bridge/modules/bridge/module.yaml, install/cluster-operator/060-Deployment-strimzi-cluster-operator.yaml, install/topic-operator/05-Deployment-strimzi-topic-operator.yaml, install/user-operator/05-Deployment-strimzi-user-operator.yaml, kafka/kafka-2.5.0/image.yaml, kafka/kafka-2.6.0/image.yaml, kafka/modules/kafka/2.5.0/module.yaml, kafka/modules/kafka/2.6.0/module.yaml, kafka/modules/kafka/base/module.yaml, operator/image.yaml, operator/modules/operator/module.yaml
To avoid customer confusion we are:
- Jumping the image version from `1.6.2` -> `1.6.4` to align with the decoupled bundle version.
- Bumping the versions for all components even though only the Kafka images changed to keep the AMQ Streams components coupled.
=> Update MD5s for AMQ Streams 1.6.4 CR1

operator-metadata/dist-git-files/container.yaml
Our brew targets are now multiarch, so we must specify our target architecture explicitly here
=> Add platform specific configuration

operator-metadata/manifests/bundle.clusterserviceversion.yaml, operator-metadata/metadata/annotations.yaml
These annotations prevent indexes being generated and bundles being installed on unsupported OCP versions.
Note the annotation in the `metadata/annotations.yaml` matches the label in our image.yaml file, this is a new requirement!
Resolves https://github.com/jboss-container-images/amqstreams-1-openshift-image/issues/283
=> Set olm.maxOpenShiftVersion

install/cluster-operator/060-Deployment-strimzi-cluster-operator.yaml
The metering labels for the Mirror Maker 2 deployment seem to be wrong with an space after `=`. This is causing followjng error when running the operator:
```
2021-11-15 21:22:49 ERROR AbstractOperator:382 - Reconciliation #35(timer) KafkaMirrorMaker2(log-setting-cluster-test/my-cluster-1432217751-mirror-maker-2): Reconciliation failed
java.lang.NoClassDefFoundError: Could not initialize class io.strimzi.operator.cluster.model.KafkaMirrorMaker2Cluster
at io.strimzi.operator.cluster.operator.assembly.KafkaMirrorMaker2AssemblyOperator.createOrUpdate(KafkaMirrorMaker2AssemblyOperator.java:138) ~[io.strimzi.cluster-operator-0.26.0.redhat-00001.jar:0.26.0.redhat-00001]
at io.strimzi.operator.cluster.operator.assembly.KafkaMirrorMaker2AssemblyOperator.createOrUpdate(KafkaMirrorMaker2AssemblyOper …
```
=> Fix incorrect space in the metering labels breaking the MM2 deployment

operator-metadata/manifests/bundle.clusterserviceversion.yaml
Fixing image SHAs manually because the bundle pipeline is still picking the old ones (from a previous 1.8.4 build).
=> Fixed image SHAs

install/cluster-operator/040-Crd-kafka.yaml, install/cluster-operator/041-Crd-kafkaconnect.yaml, install/cluster-operator/045-Crd-kafkamirrormaker.yaml, install/cluster-operator/046-Crd-kafkabridge.yaml, install/cluster-operator/048-Crd-kafkamirrormaker2.yaml, operator-metadata/manifests/kafkabridges.kafka.strimzi.io.crd.yaml, operator-metadata/manifests/kafkaconnects.kafka.strimzi.io.crd.yaml, operator-metadata/manifests/kafkamirrormaker2s.kafka.strimzi.io.crd.yaml, operator-metadata/manifests/kafkamirrormakers.kafka.strimzi.io.crd.yaml, operator-metadata/manifests/kafkas.kafka.strimzi.io.crd.yaml
The https://github.com/strimzi/strimzi-kafka-operator/pull/6434 (related to ENTMQST-3826) was cherry picked for AMQ Streams 2.1 and it means some changes on the installed CRDs.
=> Updated CRDs due to cherry-pick of ENTMQST-3826

operator-metadata/manifests/bundle.clusterserviceversion.yaml
Update Strimzi Maven Builder image to latest released OpenJDK image [1]
[1] https://catalog.redhat.com/software/containers/ubi8/openjdk-11/5dd6a4b45a13461646f677f4?container-tabs=gti&push_date=1655414540000&architecture=amd64&tag=1.13-1.1655306377
=> Update Strimzi Maven Builder image

bridge/image.yaml, drain-cleaner/image.yaml, kafka/kafka-3.2.3/image.yaml, kafka/kafka-3.3.1/image.yaml, operator/image.yaml
The `libsolv` package used by dnf for RPM dependency resolution was changed so that it doesn't always install the latest packages. This causes a stale `nss` package to be brought in as a dependency when we install java into our container images. Since the up-to-date `nss` package we need has the`crypto-policies-scripts` RPM package as a dependency ( and the stale `nss` package requires an older and different crypto-policy RPM package as a dependency), we can force the the installation of the up-to-date `nss` package by explicitly installing the `crypto-policies-scripts` RPM package.
=> Add workaround for libsolv issue

bridge/image.yaml, drain-cleaner/image.yaml, kafka/kafka-3.2.3/image.yaml, kafka/kafka-3.3.1/image.yaml, operator/image.yaml
Revert workaround in YAML files which were created for libsolv issue [1] by removing  - crypto-policies-scripts
[1] https://github.com/jboss-container-images/amqstreams-1-openshift-image/pull/381
=> Revert workaround for libsolv issue

bridge/image.yaml, drain-cleaner/image.yaml, kafka/kafka-3.1.0/image.yaml, kafka/kafka-3.2.3/image.yaml, operator/image.yaml
Revert workaround in YAML files which were created for libsolv issue [1] by removing - crypto-policies-scripts
[1] https://github.com/jboss-container-images/amqstreams-1-openshift-image/pull/381
=> Amqstreams22 dev Revert Workaround for libsolv issue

operator-metadata/image.yaml, operator-metadata/metadata/annotations.yaml
Now that we support two AMQ Streams releases at the same time which are installable via OLM, we must employ the "fancy channeling" technique on our released bundle channels.
Once Streams 2.3.0 is released, we cannot ship Streams 2.2.x releases to the `stable`and `amq-streams-2.x` channels anymore because they would have a lower semver than what is at the head of those channels.
=> Update OLM channels of Streams

kafka/modules/kafka/base/install.sh
This PR resolves #388 by reinstalling the `tzdata` RPM package using cekit modules.
Note that we are only updating the Kafka operand images since they are the only images that contain non-java tools like the kafka_exporter that need the `/usr/share/timezone` data for timezone log configuration.
Anyways, built and tested changes and everything seems to work ok!
=> Reinstall timezone data for timezone log configuration

bridge/gating.yaml, drain-cleaner/gating.yaml, kafka/kafka-3.4.0/gating.yaml, kafka/kafka-3.5.0/gating.yaml, operator-metadata/gating.yaml, operator/gating.yaml
This PR adds gating for aarch64 - new arch supported by AMQ Streams from 2.5.0
=> Add systemtest gating for aarch64

operator-metadata/automation/README.md, operator-metadata/automation/__init__.py, operator-metadata/automation/main.py, operator-metadata/automation/modules/__init__.py, operator-metadata/automation/modules/bundle_automation.py, operator-metadata/automation/modules/constants.py, operator-metadata/automation/modules/file.py, operator-metadata/automation/tests/__init__.py, operator-metadata/automation/tests/resources/CONTAINER_BUILDS_BRIDGE_BUILD_INFO_JSON, operator-metadata/automation/tests/resources/CONTAINER_BUILDS_DRAIN_CLEANER_BUILD_INFO_JSON, operator-metadata/automation/tests/resources/CONTAINER_BUILDS_KAFKA_34_BUILD_INFO_JSON, operator-metadata/automation/tests/resources/CONTAINER_BUILDS_KAFKA_35_BUILD_INFO_JSON, operator-metadata/automation/tests/resources/CONTAINER_BUILDS_OPERATOR_BUILD_INFO_JSON, operator-metadata/automation/tests/resources/test.bundle.clusterserviceversion.yaml, operator-metadata/automation/tests/resources/test.image.yaml, operator-metadata/automation/tests/test_bundle_automation.py, operator-metadata/image.yaml
Up until now, the automation scripts for updating our bundle metadata have lived in internal git repos making them difficult to update and collaborate on. Centralizing the scripts here will make them easier to work on and sync across internal git repos that need the scripts.
These automation scripts are automatically synced with internal git repos and executed as part of the CPaaS container build pipeline:
```
(1) CPaaS builds container images
(2) CPaaS executes these automation scripts, updating bundle metadata 
(3) CPaaS builds bundle image using updated bundle metadata 
```
=> Add bundle automation

install/cluster-operator/040-Crd-kafka.yaml, install/cluster-operator/041-Crd-kafkaconnect.yaml, install/cluster-operator/044-Crd-kafkauser.yaml, install/cluster-operator/045-Crd-kafkamirrormaker.yaml, install/cluster-operator/046-Crd-kafkabridge.yaml, install/cluster-operator/047-Crd-kafkaconnector.yaml, install/cluster-operator/048-Crd-kafkamirrormaker2.yaml, install/cluster-operator/04A-Crd-kafkanodepool.yaml, install/cluster-operator/050-ConfigMap-strimzi-cluster-operator.yaml, install/drain-cleaner/openshift/021-Role.yaml, install/drain-cleaner/openshift/031-RoleBinding.yaml, install/drain-cleaner/openshift/060-Deployment.yaml, install/user-operator/04-Crd-kafkauser.yaml
We missed backporting the CRDs when doing the original update to our install files. 
This PR adds the missing updates
=> Update CRDs for AMQ Streams 2.6.0 release

proxy/gating.yaml
We need to enable the gating for Proxy in x86, that is the only architecture currently supported.
That will apply some kind of requirements before we can proceed with the release.
=> enabling gating for x86

examples/proxy/record-encryption/load-balancer/README.md
why: the proxy example relies on Kafka CLI tools, it should be using the tools from the distribution shipped as part of AMQ Streams rather than encouraging the user to go upstream.
=> Use the Kafka CLI from the AMQ Streams distribution.

proxy/image.yaml
As part of the FIPS work, the contentset used need to be in sync with the base image.
=> Switch to contentset in sync with the base image.

examples/proxy/record-encryption/base/proxy/proxy-deployment.yaml, examples/proxy/record-encryption/cluster-ip/README.md, examples/proxy/record-encryption/load-balancer/README.md
The example content needs to refer to the downstream proxy image, rather than the upstream one.
As per https://issues.redhat.com/browse/SPMM-16330, we will refer to it by floating tag (x.y), in order to obviate the need to refresh the example content if the AMQ Streams is re-released.
https://errata.devel.redhat.com/package/show/amqstreams-proxy-container
https://errata.devel.redhat.com/package/show/amqstreams-kafka-37-container
#460
=> Update example to refer to published downstream proxy image

proxy/image.yaml
Trying to influence Cekit to prevent dnf from install weak-dependencies.
why: the RPM transaction was installing things like dracut, which is pulling in grub!  We don't want these in AMQ Streams images!
https://docs.cekit.io/en/latest/descriptor/image.html#package-manager-flags
=> (Experiment) Suppress installation of weak dependencies

bridge/image.yaml, drain-cleaner/image.yaml, kafka/kafka-3.6.0/image.yaml, kafka/kafka-3.7.0/image.yaml, operator/image.yaml
Having changed to a new base image, the following addition is needed for the rpm definition: `-eus-rpms__8_DOT_6`
=> Refactor content sets for rhel8-els image

proxy/image.yaml
This is no longer required as we are switching to RHEL-9.
=> Remove experiment that tied container to specific nss version

examples/proxy/record-encryption/cluster-ip/README.md
The container command line for creating the topic is incorrect.
It looks like the documentation has the command line correct
https://docs.redhat.com/en/documentation/red_hat_streams_for_apache_kafka/2.7/html/using_the_streams_for_apache_kafka_proxy/proc-deploying-proxy-str#proc-deploying-proxy-str
=> Bug fix to example content

maven-builder/image.yaml
use maven-openjdk17 rather than `maven` to avoid a OpenJDK 11 being installed in the image.
=> ENTMQST-6192: use maven-openjdk17

bridge/image.yaml, bridge/modules/bridge/module.yaml, drain-cleaner/image.yaml, drain-cleaner/modules/drain-cleaner/module.yaml, kafka/kafka-3.6.0/image.yaml, kafka/kafka-3.7.0/image.yaml, kafka/modules/kafka/base/module.yaml, maven-builder/image.yaml, maven-builder/modules/maven-builder/module.yaml, operator/image.yaml, operator/modules/operator/module.yaml
Red Hat now has a RHEL analogue for the UBI minimal.  Switching to this will reduce our container sizes and reduce the possibility for spurious CVEs.
This switches to the minimal base image, and reverts the package manager back to microdnf.  It also removes the package removals we added to slim down the fat image.
I tested this change against Proxy - no issues found.
=> ENTMQST-6263: Switch to FIPS friendly 9.2 minimal base image

examples/proxy/README.md, examples/proxy/record-validation/README.md, examples/proxy/record-validation/base/kafka/kafka-namespace.yaml, examples/proxy/record-validation/base/kafka/kafka-persistent.yaml, examples/proxy/record-validation/base/kafka/kustomization.yaml, examples/proxy/record-validation/base/kustomization.yaml, examples/proxy/record-validation/base/proxy/kustomization.yaml, examples/proxy/record-validation/base/proxy/proxy-deployment.yaml, examples/proxy/record-validation/base/proxy/proxy-namespace.yaml, examples/proxy/record-validation/base/proxy/proxy-pod-monitor.yaml, examples/proxy/record-validation/base/schema-registry/kustomization.yaml, examples/proxy/record-validation/base/schema-registry/schema-registry-namespace.yaml, examples/proxy/record-validation/base/schema-registry/schema-registry-registry.yaml, examples/proxy/record-validation/cluster-ip/README.md, examples/proxy/record-validation/cluster-ip/kustomization.yaml, examples/proxy/record-validation/cluster-ip/proxy/kustomization.yaml, examples/proxy/record-validation/cluster-ip/proxy/proxy-config.yaml, examples/proxy/record-validation/cluster-ip/proxy/proxy-service.yaml, examples/proxy/record-validation/load-balancer/README.md, examples/proxy/record-validation/load-balancer/kustomization.yaml, examples/proxy/record-validation/load-balancer/proxy/kustomization.yaml, examples/proxy/record-validation/load-balancer/proxy/proxy-config.yaml, examples/proxy/record-validation/load-balancer/proxy/proxy-service.yaml, examples/proxy/record-validation/record-examples/invalid-person-invalid-age.json, examples/proxy/record-validation/record-examples/invalid-person-malformed.json, examples/proxy/record-validation/record-examples/valid-person.json, examples/proxy/record-validation/schemas/person.schema.json
ENTMQSTPR-48: record validation example
why: 2.8 supports record validation against JSON schemas in Apicurio Schema Registry.
Note: When testing the example, switch the image to the upstream.'s
quay.io/kroxylicious/kroxylicious:0.8.0
=> ENTMQSTPR-47: Record validation example with Red Hat build of Apicurio Registry

kafka/kafka-3.7.0/image.yaml, kafka/kafka-3.8.0/image.yaml, kafka/modules/kafka/base/install.sh, kafka/modules/kafka/base/module.yaml
Stunnel was removed from upstream repo. Having it in `install.sh` is causing the Kafka image builds to fail.
=> Remove stunnel from Kafka scripts

install/cluster-operator/060-Deployment-strimzi-cluster-operator.yaml, operator-metadata/manifests/bundle.clusterserviceversion.yaml
The `securtityContext` field is to be removed from Cluster Operator Deployment and OLM Deployment yamls for the current CR.
=> Revert securityContext yaml fields

operator-metadata/container.yaml
Refactor `container.yaml` fields to the value of `false` to fix the bundle image build issue.
`enable_repo_replacements: false`
`enable_registry_replacements: false`
=> Revert container.yaml fileds to enable bundle build

kafka/kafka-3.7.0/image.yaml, kafka/kafka-3.8.0/image.yaml
This configuration allows us to install candidate release RPM builds into our container images before those RPM builds are released to production pulp repos. This allows us to build and release all of our components:
- artifacts
- RPMs
- containers
At the same time. Up until now, we have always had to release RPMs to production repos ahead of our actual GA release.
=> Enable installation of unreleased RPMs

operator-metadata/manifests/bundle.clusterserviceversion.yaml
In order to force build Kafka 36 to pull in the new base image, we need to revert the latest bot commit and rereun pipelines.
=> Remove bot commit for force build

operator-metadata/image.yaml, operator-metadata/manifests/bundle.clusterserviceversion.yaml, operator-metadata/metadata/annotations.yaml
Updating supported OCP versions to corrolate with the release dashboard versions. 4.12 - 4.16
=> Update ocp to 4.12

operator-metadata/automation/tests/resources/test.image.yaml
Update test image to ocp versions 4.12 to corrolate with the changes made in `operator-metadata`
=> update test image to ocp versions 4.12

install/cluster-operator/060-Deployment-strimzi-cluster-operator.yaml, operator-metadata/manifests/bundle.clusterserviceversion.yaml
Removing the Entity OPerator TLS sidecar image configuration from the YAML Deployment and OLM deployment.
=> Remove Entity Operator TLS sidecar image configuration from YAMLs
