jboss-container-images/amqstreams-1-openshift-image

- README.adoc
- kafka-stunnel/image.yaml
- kafka-stunnel/modules/os-stunnel-launch/added/scripts/stunnel_config_generator.sh
- kafka-stunnel/modules/os-stunnel-launch/added/scripts/stunnel_run.sh
- kafka-stunnel/modules/os-stunnel-launch/install.sh
- kafka-stunnel/modules/os-stunnel-launch/module.yaml
- stunnel-base/image.yaml
- stunnel-base/modules/os-stunnel-install/install.sh
- stunnel-base/modules/os-stunnel-install/module.yaml
- topic-operator-stunnel/image.yaml
- topic-operator-stunnel/modules/os-stunnel-launch/added/scripts/stunnel_config_generator.sh
- topic-operator-stunnel/modules/os-stunnel-launch/added/scripts/stunnel_run.sh
- topic-operator-stunnel/modules/os-stunnel-launch/install.sh
- topic-operator-stunnel/modules/os-stunnel-launch/module.yaml
- zookeeper-stunnel/image.yaml
- zookeeper-stunnel/modules/os-stunnel-launch/added/scripts/stunnel_config_generator.sh
- zookeeper-stunnel/modules/os-stunnel-launch/added/scripts/stunnel_run.sh
- zookeeper-stunnel/modules/os-stunnel-launch/install.sh
- zookeeper-stunnel/modules/os-stunnel-launch/module.yaml
https://github.com/jboss-container-images/jboss-amqstreams-1-openshift-image/issues/8
> Add Stunnel Images

- Makefile
- Makefile.docker
- cluster-operator/Makefile
- kafka-base/Makefile
- kafka-connect-s2i/Makefile
- kafka-connect/Makefile
- kafka-stunnel/Makefile
- kafka/Makefile
- stunnel-base/Makefile
- topic-operator-stunnel/Makefile
- topic-operator/Makefile
- zookeeper-stunnel/Makefile
- zookeeper/Makefile
> Adding Makefiles

- Makefile
- entity-operator-stunnel/Makefile
- entity-operator-stunnel/image.yaml
- entity-operator-stunnel/modules/os-stunnel-launch/added/scripts/stunnel_config_generator.sh
- entity-operator-stunnel/modules/os-stunnel-launch/added/scripts/stunnel_run.sh
- entity-operator-stunnel/modules/os-stunnel-launch/install.sh
- entity-operator-stunnel/modules/os-stunnel-launch/module.yaml
Issue: https://github.com/jboss-container-images/jboss-amqstreams-1-openshift-image/issues/15
> Adding entity operator stunnel image

- Makefile
- user-operator/Makefile
- user-operator/image.yaml
- user-operator/modules/os-user-operator-install/added/scripts/user_operator_run.sh
- user-operator/modules/os-user-operator-install/install.sh
- user-operator/modules/os-user-operator-install/module.yaml
Issue: https://github.com/jboss-container-images/jboss-amqstreams-1-openshift-image/issues/14
> Adding User Operator Image

- cluster-operator/image.yaml
- cluster-operator/modules/cluster-operator/install.sh
- topic-operator/image.yaml
- topic-operator/modules/topic-operator/install.sh
Not refactoring templates/ dir as this dir will be replaced in a future PR with corrected names
> Refactor controller -> operator (missed on first refactor)

- Makefile
- cluster-operator/image.yaml
- java-base/Makefile
- java-base/image.yaml
- java-base/modules/os-javabase-install/install.sh
- java-base/modules/os-javabase-install/module.yaml
- java-base/modules/os-javabase-install/scripts/launch_java.sh
- topic-operator/image.yaml
Issue: https://github.com/jboss-container-images/jboss-amqstreams-1-openshift-image/issues/6
> Adding java-base image

- Makefile
- kafka-init/Makefile
- kafka-init/image.yaml
- kafka-init/modules/os-kafka-init-install/added/scripts/kafka_init_run.sh
- kafka-init/modules/os-kafka-init-install/install.sh
- kafka-init/modules/os-kafka-init-install/module.yaml
(4) Fourth unit to review. Although this isn't exactly complete, (We still need to swap in the "official" jar and checksum), I think it would still be good to review(possibly merge) the scripts. I'll update the Image descriptor file to point to the proper jar once we have them. WDYT?
Issue: https://github.com/jboss-container-images/jboss-amqstreams-1-openshift-image/issues/7
> Adding kafka-init image

- kafka-base/image.yaml
- kafka-connect/modules/kafka-connect/added/scripts/kafka_connect_run.sh
- kafka/modules/kafka/added/scripts/kafka_run.sh
- zookeeper/modules/zookeeper/added/scripts/zookeeper_run.sh
https://github.com/jboss-container-images/jboss-amqstreams-1-openshift-image/issues/32
> Fix dynamic-resources scripts

- topic-operator/image.yaml
- topic-operator/modules/topic-operator/added/scripts/tls_prepare_certificates.sh
- topic-operator/modules/topic-operator/added/scripts/topic_operator_run.sh
- topic-operator/modules/topic-operator/install.sh
Issue: https://github.com/jboss-container-images/jboss-amqstreams-1-openshift-image/issues/35
> Backporting enhanced Topic Operator scripts

- user-operator/image.yaml
- user-operator/modules/os-user-operator-install/added/scripts/user_operator_run.sh
- user-operator/modules/os-user-operator-install/install.sh
Issue: https://github.com/jboss-container-images/jboss-amqstreams-1-openshift-image/issues/34
> Fix User Operator scripts

- cluster-operator/image.yaml
- entity-operator-stunnel/image.yaml
- examples/install/cluster-operator/05-Deployment-strimzi-cluster-operator.yaml
- examples/install/topic-operator/05-Deployment-strimzi-topic-operator.yaml
- examples/install/user-operator/05-Deployment-strimzi-user-operator.yaml
- java-base/image.yaml
- kafka-base/image.yaml
- kafka-connect-s2i/image.yaml
- kafka-connect/image.yaml
- kafka-init/image.yaml
- kafka-stunnel/image.yaml
- kafka/image.yaml
- modules/common/java/module.yaml
- stunnel-base/image.yaml
- topic-operator/image.yaml
- user-operator/image.yaml
- zookeeper-stunnel/image.yaml
- zookeeper/image.yaml
Issue: https://github.com/jboss-container-images/jboss-amqstreams-1-openshift-image/issues/30
Issue: https://github.com/jboss-container-images/jboss-amqstreams-1-openshift-image/issues/33
> Update release names

- cluster-operator/content_sets.yml
- entity-operator-stunnel/content_sets.yml
- java-base/content_sets.yml
- kafka-base/content_sets.yml
- kafka-connect-s2i/content_sets.yml
- kafka-connect/content_sets.yml
- kafka-init/content_sets.yml
- kafka-mirror-maker/content_sets.yml
- kafka-stunnel/content_sets.yml
- kafka/content_sets.yml
- stunnel-base/content_sets.yml
- topic-operator/content_sets.yml
- user-operator/content_sets.yml
- zookeeper-stunnel/content_sets.yml
- zookeeper/content_sets.yml
Add the content_sets.yml file to all container images.
> Add content_sets.yml files

- cluster-operator/help.md
- entity-operator-stunnel/help.md
- java-base/help.md
- kafka-base/help.md
- kafka-connect-s2i/help.md
- kafka-connect/help.md
- kafka-init/help.md
- kafka-mirror-maker/help.md
- kafka-stunnel/help.md
- kafka/help.md
- stunnel-base/help.md
- topic-operator/help.md
- user-operator/help.md
- zookeeper-stunnel/help.md
- zookeeper/help.md
This PR adds help.md files for each image.
> Add help.md files

- stunnel-base/image.yaml
- stunnel-base/modules/stunnel-base/install.sh
- stunnel-base/modules/stunnel-base/scripts/stunnel_healthcheck.sh
> Stunnel health checks

- cluster-operator/image.yaml
- entity-operator-stunnel/image.yaml
- java-base/image.yaml
- kafka-base/image.yaml
- kafka-connect-s2i/image.yaml
- kafka-connect/image.yaml
- kafka-init/image.yaml
- kafka-mirror-maker/image.yaml
- kafka-stunnel/image.yaml
- kafka/image.yaml
- stunnel-base/image.yaml
- topic-operator/image.yaml
- user-operator/image.yaml
- zookeeper-stunnel/image.yaml
- zookeeper/image.yaml
This PR includes changes that:
1. Migrate images off of unsupported CE images to get CVE patches and Freshmaker support
2. Updates configuration necessary for installing signed RPMs
> Removed CE image dependency; Added osbs container.yaml configuration

- chain/build.py
- chain/config.py
- chain/generator.py
- chain/image.py
Minor fixes for using automation tool for building the images. Will be useful for our next CVE respin
> Fixing branch override for chain build automation

- operator/manifests/amq-streams-kafkas.crd.yaml
- operator/manifests/amq-streams.v1.2.0.clusterserviceversion.yaml
Some changes to the OLM files supplied by @stanlyDoge
> OLM updates and fixes

- operator/modules/olm/manifests/amq-streams.v1.2.0.clusterserviceversion.yaml
This PR delivers some further bug-fixes to the OLM manifest.
> Some further bug-fixes for manifests

- install/cluster-operator/050-Deployment-strimzi-cluster-operator.yaml
This PR adds the 3Scale discovery annotations which we should use in 1.3 release.
> Add the 3Scale discovery annotations

- kafka/kafka-2.1.1/image.yaml
- kafka/kafka-2.2.1/image.yaml
- kafka/modules/kafka/install.sh
- kafka/modules/kafka/scripts/kafka_run.sh
> Remove Strimzi version from the kafka-agent artifact name

- operator/image.yaml
> Removed manifests from the operator image

- bridge/image.yaml
- bridge/modules/bridge/install.sh
- bridge/modules/bridge/module.yaml
- kafka/kafka-2.3.0/image.yaml
- kafka/kafka-2.4.0/image.yaml
- kafka/modules/kafka/base/install.sh
- kafka/modules/kafka/base/module.yaml
- operator/image.yaml
- operator/modules/operator/install.sh
- operator/modules/operator/module.yaml
Removed cct_module
Added packages installation (previously got by the "user" module)
Added strimzi 1001 user (fixes #139)
> Removed cct_module and changing to strimzi user

- common/modules/olm/manifests/1.4.0/amq-streams-entityoperator.clusterrole.yaml
- common/modules/olm/manifests/1.4.0/amq-streams-kafkabridges.crd.yaml
- common/modules/olm/manifests/1.4.0/amq-streams-kafkabroker.clusterrole.yaml
- common/modules/olm/manifests/1.4.0/amq-streams-kafkaconnectors.crd.yaml
- common/modules/olm/manifests/1.4.0/amq-streams-kafkaconnects.crd.yaml
- common/modules/olm/manifests/1.4.0/amq-streams-kafkaconnects2is.crd.yaml
- common/modules/olm/manifests/1.4.0/amq-streams-kafkamirrormakers.crd.yaml
- common/modules/olm/manifests/1.4.0/amq-streams-kafkamirrormakers2.crd.yaml
- common/modules/olm/manifests/1.4.0/amq-streams-kafkas.crd.yaml
- common/modules/olm/manifests/1.4.0/amq-streams-kafkatopics.crd.yaml
- common/modules/olm/manifests/1.4.0/amq-streams-kafkausers.crd.yaml
- common/modules/olm/manifests/1.4.0/amq-streams-topicoperator.clusterrole.yaml
- common/modules/olm/manifests/1.4.0/amq-streams.v1.4.0.clusterserviceversion.yaml
- common/modules/olm/manifests/amq-streams.package.yaml
Added CSV and CRDs YAML files for 1.4.0
Updated package file to 1.4.0
> CSV and CRDs for 1.4.0

- common/modules/olm/manifests/1.4.0/amq-streams.v1.4.0.clusterserviceversion.yaml
Fixed bridge image
Reducing relatedImages as Strimzi upstream in community operators
> Fixing bridge image and reducing relatedImages

- bridge/modules/bridge/module.yaml
- kafka/modules/kafka/2.3.0/module.yaml
- kafka/modules/kafka/2.4.0/module.yaml
- operator/modules/operator/module.yaml
> Update MD5s for AMQ Streams 1.4.0 CR1

- bridge/modules/bridge/module.yaml
- kafka/modules/kafka/2.3.0/module.yaml
- kafka/modules/kafka/2.4.0/module.yaml
- operator/modules/operator/module.yaml
> Update MD5s for AMQ Streams 1.4.0 CR3

- common/modules/olm/manifests/1.4.0/amq-streams.v1.4.0.clusterserviceversion.yaml
> Updated metadata image SHAs for 1.4.0 CR3

- common/modules/olm/manifests/1.4.0/amq-streams.v1.4.0.clusterserviceversion.yaml
> Update unsupported manifest list SHAs to manifest SHAs

- common/modules/olm/manifests/1.4.0/amq-streams.v1.4.0.clusterserviceversion.yaml
> Updated metadata image SHAs for 1.4.0 CR4

- common/modules/olm/manifests/1.4.0/amq-streams.v1.4.0.clusterserviceversion.yaml
> Update containerImage annotation to use SHA in metadata image

- kafka/modules/kafka/2.3.0/module.yaml
- kafka/modules/kafka/2.4.0/module.yaml
- operator/modules/operator/module.yaml
> Update MD5s for AMQ Streams 1.4.0 CR5

- common/modules/olm/manifests/1.4.0/amq-streams.v1.4.0.clusterserviceversion.yaml
> Updated metadata image SHAs for 1.4.0 CR5

- bridge/image.yaml
- bridge/modules/bridge/module.yaml
- common/modules/olm/manifests/1.4.1/amq-streams-entityoperator.clusterrole.yaml
- common/modules/olm/manifests/1.4.1/amq-streams-kafkabridges.crd.yaml
- common/modules/olm/manifests/1.4.1/amq-streams-kafkabroker.clusterrole.yaml
- common/modules/olm/manifests/1.4.1/amq-streams-kafkaconnectors.crd.yaml
- common/modules/olm/manifests/1.4.1/amq-streams-kafkaconnects.crd.yaml
- common/modules/olm/manifests/1.4.1/amq-streams-kafkaconnects2is.crd.yaml
- common/modules/olm/manifests/1.4.1/amq-streams-kafkamirrormakers.crd.yaml
- common/modules/olm/manifests/1.4.1/amq-streams-kafkamirrormakers2.crd.yaml
- common/modules/olm/manifests/1.4.1/amq-streams-kafkas.crd.yaml
- common/modules/olm/manifests/1.4.1/amq-streams-kafkatopics.crd.yaml
- common/modules/olm/manifests/1.4.1/amq-streams-kafkausers.crd.yaml
- common/modules/olm/manifests/1.4.1/amq-streams-topicoperator.clusterrole.yaml
- common/modules/olm/manifests/1.4.1/amq-streams.v1.4.1.clusterserviceversion.yaml
- common/modules/olm/manifests/amq-streams.package.yaml
- common/modules/olm/module.yaml
- install/cluster-operator/050-Deployment-strimzi-cluster-operator.yaml
- install/topic-operator/05-Deployment-strimzi-topic-operator.yaml
- install/user-operator/05-Deployment-strimzi-user-operator.yaml
- kafka/kafka-2.3.0/image.yaml
- kafka/kafka-2.4.0/image.yaml
- kafka/modules/kafka/2.3.0/module.yaml
- kafka/modules/kafka/2.4.0/module.yaml
- kafka/modules/kafka/base/module.yaml
- operator-metadata/image.yaml
- operator/image.yaml
- operator/modules/operator/module.yaml
Another PR will come for updating SHAs when images are built.
> Updates for AMQ Streams 1.4.1

- common/modules/olm/manifests/1.4.1/amq-streams.v1.4.1.clusterserviceversion.yaml
> Updating metadata SHAs for OpenJDK8 CVE respin

- install/cluster-operator/050-Deployment-strimzi-cluster-operator.yaml
Found a this typo when debugging a customer issue, the officially released files are fine, it's just the developer copy that needs to be fixed
> Fix deployment files for 1.2.0 release

- kafka/modules/kafka/2.4.0/install.sh
- kafka/modules/kafka/2.4.0/module.yaml
- kafka/modules/kafka/2.5.0/install.sh
- kafka/modules/kafka/2.5.0/module.yaml
This PR changes the Kafka zip artifacts name to reflects the ones that we have in PNC to avoid confusion.
> Changed Kafka related zip files names

- bridge/modules/bridge/module.yaml
- kafka/modules/kafka/2.4.0/module.yaml
- kafka/modules/kafka/2.5.0/module.yaml
- kafka/modules/kafka/base/install.sh
- kafka/modules/kafka/base/module.yaml
- operator/modules/operator/module.yaml
> Update MD5s for AMQ Streams 1.5.0

- common/modules/olm/install.sh
I forgot this change, but it is that last one!
> Revert olm install script to old manifest format

- common/modules/olm/install.sh
> Fixing another typo in OLM format reversion

- bridge/modules/bridge/module.yaml
- kafka/modules/kafka/2.4.0/module.yaml
- kafka/modules/kafka/2.5.0/module.yaml
- kafka/modules/kafka/base/module.yaml
- operator/modules/operator/module.yaml
> Update MD5s for AMQ Streams 1.5.0 CR2

- common/modules/olm/manifests/1.5.0/amq-streams.v1.5.0.clusterserviceversion.yaml
> Update SHAs in OLM files for AMQ Streams 1.5.0 CR2

- bridge/image.yaml
- kafka/kafka-2.4.0/image.yaml
- kafka/kafka-2.5.0/image.yaml
- kafka/modules/kafka/base/install.sh
- operator/image.yaml
- operator/modules/operator/install.sh
I made a mistake when I was rebasing the amqstreams16-dev branch off of the amqstreams15-dev branch and accidentally merged the original PR. I have fixed the source and had to open a new PR here
> Adding tini package

- common/modules/olm/manifests/1.5.2/amq-streams-entityoperator.clusterrole.yaml
- common/modules/olm/manifests/1.5.2/amq-streams-kafkabridges.crd.yaml
- common/modules/olm/manifests/1.5.2/amq-streams-kafkabroker.clusterrole.yaml
- common/modules/olm/manifests/1.5.2/amq-streams-kafkaconnectors.crd.yaml
- common/modules/olm/manifests/1.5.2/amq-streams-kafkaconnects.crd.yaml
- common/modules/olm/manifests/1.5.2/amq-streams-kafkaconnects2is.crd.yaml
- common/modules/olm/manifests/1.5.2/amq-streams-kafkamirrormakers.crd.yaml
- common/modules/olm/manifests/1.5.2/amq-streams-kafkamirrormakers2.crd.yaml
- common/modules/olm/manifests/1.5.2/amq-streams-kafkarebalances.crd.yaml
- common/modules/olm/manifests/1.5.2/amq-streams-kafkas.crd.yaml
- common/modules/olm/manifests/1.5.2/amq-streams-kafkatopics.crd.yaml
- common/modules/olm/manifests/1.5.2/amq-streams-kafkausers.crd.yaml
- common/modules/olm/manifests/1.5.2/amq-streams-topicoperator.clusterrole.yaml
- common/modules/olm/manifests/1.5.2/amq-streams.v1.5.2.clusterserviceversion.yaml
- common/modules/olm/manifests/amq-streams.package.yaml
- common/modules/olm/module.yaml
- operator-metadata/image.yaml
Updated to operator metadata image 1.5.2
> Updated images SHAs for CVE-2020-12049 respin

- bridge/image.yaml
- kafka/kafka-2.4.0/image.yaml
- kafka/kafka-2.5.0/image.yaml
- operator-metadata/image.yaml
- operator/image.yaml
> Added maintainer label

- bridge/image.yaml
- kafka/kafka-2.4.0/image.yaml
- kafka/kafka-2.5.0/image.yaml
- operator-metadata/image.yaml
- operator/image.yaml
> Added platform specific OSBS configuration

- common/modules/olm/manifests/1.5.3/amq-streams-entityoperator.clusterrole.yaml
- common/modules/olm/manifests/1.5.3/amq-streams-kafkabridges.crd.yaml
- common/modules/olm/manifests/1.5.3/amq-streams-kafkabroker.clusterrole.yaml
- common/modules/olm/manifests/1.5.3/amq-streams-kafkaconnectors.crd.yaml
- common/modules/olm/manifests/1.5.3/amq-streams-kafkaconnects.crd.yaml
- common/modules/olm/manifests/1.5.3/amq-streams-kafkaconnects2is.crd.yaml
- common/modules/olm/manifests/1.5.3/amq-streams-kafkamirrormakers.crd.yaml
- common/modules/olm/manifests/1.5.3/amq-streams-kafkamirrormakers2.crd.yaml
- common/modules/olm/manifests/1.5.3/amq-streams-kafkarebalances.crd.yaml
- common/modules/olm/manifests/1.5.3/amq-streams-kafkas.crd.yaml
- common/modules/olm/manifests/1.5.3/amq-streams-kafkatopics.crd.yaml
- common/modules/olm/manifests/1.5.3/amq-streams-kafkausers.crd.yaml
- common/modules/olm/manifests/1.5.3/amq-streams-topicoperator.clusterrole.yaml
- common/modules/olm/manifests/1.5.3/amq-streams.v1.5.3.clusterserviceversion.yaml
- common/modules/olm/manifests/amq-streams.package.yaml
- common/modules/olm/module.yaml
- operator-metadata/image.yaml
> Updated images SHAs for CVE-2020:57238 respin

- kafka/modules/kafka/2.4.0/module.yaml
- kafka/modules/kafka/2.5.0/module.yaml
> Hotfix for ENTMQST-2238

- operator/modules/operator/module.yaml
> Hotfix for ENTMQST-2238 (Part two: CO update)

- bridge/image.yaml
- kafka/kafka-2.5.0/image.yaml
- kafka/kafka-2.6.0/image.yaml
- operator/image.yaml
Resolves https://github.com/jboss-container-images/amqstreams-1-openshift-image/issues/239
Waiting on OSBS to make sure the builds work properly with this change
> Update deprecated base image names

- operator/image.yaml
Resolves https://github.com/jboss-container-images/amqstreams-1-openshift-image/issues/264
> Add bind-utils to operator image

- bridge/modules/bridge/module.yaml
- kafka/modules/kafka/base/module.yaml
- operator/modules/operator/module.yaml
> Update MD5s for AMQ Streams 1.7.0 RC2

- bridge/image.yaml
- bridge/modules/bridge/module.yaml
- kafka/kafka-2.7.0/image.yaml
- kafka/kafka-2.8.0/image.yaml
- kafka/modules/kafka/base/module.yaml
- operator-metadata/manifests/bundle.clusterserviceversion.yaml
- operator/image.yaml
- operator/modules/operator/module.yaml
- Add CSV arch label for x86_64
- Enable ppc64le
/cc @kyguy
> Enable ppc64le

- kafka/kafka-2.8.0/image.yaml
- kafka/kafka-3.0.0/image.yaml
- kafka/modules/kafka/2.8.0/install.sh
- kafka/modules/kafka/3.0.0/install.sh
- kafka/modules/kafka/base/install.sh
- kafka/modules/kafka/base/module.yaml
> Install kafka_exporter as an RPM

- kafka/modules/kafka/2.5.0/module.yaml
- kafka/modules/kafka/2.6.0/module.yaml
- kafka/modules/kafka/base/module.yaml
Signed-off-by: Paolo Patierno <ppatierno@live.com>
> Fixed MD5 for Kafka related artifacts

- bridge/modules/bridge/module.yaml
- drain-cleaner/modules/drain-cleaner/module.yaml
- kafka/modules/kafka/base/module.yaml
- operator/modules/operator/module.yaml
> Removed content_sets from modules because ignored by cekit

- tools/report.sh
This backports the `report.sh` script as per discussions around availability/distribution of this script to some customers.
> Backport Strimzi tools/report.sh script

- tools/report.sh
Trivial PR to get the last fix on the report tool from upstream Strimzi here https://github.com/strimzi/strimzi-kafka-operator/pull/8902
> Updated report tool with fix on gathering logs from multiple CO replicas

- install/cluster-operator/060-Deployment-strimzi-cluster-operator.yaml
- operator-metadata/manifests/bundle.clusterserviceversion.yaml
Update MAVEN_BUILDER image to OpenJDK 17 image [1]
[1] https://catalog.redhat.com/software/containers/ubi8/openjdk-17/618bdbf34ae3739687568813?container-tabs=overview
> Update MAVEN_BUILDER image to OpenJDK 17 image

- bridge/modules/bridge/module.yaml
- kafka/modules/kafka/3.4.0/module.yaml
- kafka/modules/kafka/3.5.0/module.yaml
- kafka/modules/kafka/base/module.yaml
- operator/modules/operator/module.yaml
Update MD5s for newest 2.5.0 build
> Update MD5s for 2.5.0

- bridge/modules/bridge/module.yaml
- kafka/modules/kafka/3.4.0/module.yaml
- kafka/modules/kafka/3.5.0/module.yaml
- kafka/modules/kafka/base/module.yaml
- operator/modules/operator/module.yaml
> Update md5s for 2.5 CR3

- operator-metadata/manifests/bundle.clusterserviceversion.yaml
OpenShift is changing the annotations describing the features supported by the various operators. The PR adds the updated annotations to our CSV files.
> Add new infrastructure annotations to our OLM CSV file 

- bridge/image.yaml
- bridge/modules/bridge/module.yaml
- drain-cleaner/image.yaml
- drain-cleaner/modules/drain-cleaner/module.yaml
- examples/security/keycloak-authorization/kafka-authz-realm.json
- install/cluster-operator/060-Deployment-strimzi-cluster-operator.yaml
- install/drain-cleaner/openshift/060-Deployment.yaml
- install/topic-operator/05-Deployment-strimzi-topic-operator.yaml
- install/user-operator/05-Deployment-strimzi-user-operator.yaml
- kafka/kafka-3.4.0/image.yaml
- kafka/kafka-3.5.0/image.yaml
- kafka/modules/kafka/3.4.0/module.yaml
- kafka/modules/kafka/3.5.0/module.yaml
- kafka/modules/kafka/base/module.yaml
- operator-metadata/image.yaml
- operator-metadata/manifests/bundle.clusterserviceversion.yaml
- operator/image.yaml
- operator/modules/operator/module.yaml
update modules/examples to 2.5.1
> update modules/examples to 2.5.1

- tools/report.sh
Updates `tools/report.sh` with latest fix from upstream Strimzi ([#9145](https://github.com/strimzi/strimzi-kafka-operator/pull/9145))
> Updated report.sh with fix for missing CO replicaset and pod YAMLs

- bridge/modules/bridge/module.yaml
- kafka/modules/kafka/3.5.0/module.yaml
- kafka/modules/kafka/3.6.0/module.yaml
- kafka/modules/kafka/base/module.yaml
- operator/modules/operator/module.yaml
Update Md5s Again as new binaries have been added.
> Update Md5s Again

- operator-metadata/image.yaml
- operator-metadata/metadata/annotations.yaml
Add amq-streams-lts to OLM channel in Operator-Data
> Add amq-streams-lts to OLM channel 

- examples/kafka/nodepools/README.md
- examples/kafka/nodepools/kafka-with-dual-role-kraft-nodes.yaml
- examples/kafka/nodepools/kafka-with-kraft-ephemeral.yaml
- examples/kafka/nodepools/kafka-with-kraft.yaml
- examples/metrics/grafana-dashboards/strimzi-kafka.json
- examples/metrics/grafana-dashboards/strimzi-zookeeper.json
- examples/metrics/kafka-metrics.yaml
Some Upstream example files were not copied. This PR fixes the issue
> Examples files fixes

- install/cluster-operator/020-ClusterRole-strimzi-cluster-operator-role.yaml
- install/cluster-operator/023-ClusterRole-strimzi-cluster-operator-role.yaml
- install/cluster-operator/031-ClusterRole-strimzi-entity-operator.yaml
- install/cluster-operator/040-Crd-kafka.yaml
- install/cluster-operator/041-Crd-kafkaconnect.yaml
- install/cluster-operator/042-Crd-strimzipodset.yaml
- install/cluster-operator/043-Crd-kafkatopic.yaml
- install/cluster-operator/044-Crd-kafkauser.yaml
- install/cluster-operator/045-Crd-kafkamirrormaker.yaml
- install/cluster-operator/046-Crd-kafkabridge.yaml
- install/cluster-operator/047-Crd-kafkaconnector.yaml
- install/cluster-operator/048-Crd-kafkamirrormaker2.yaml
- install/cluster-operator/049-Crd-kafkarebalance.yaml
- install/cluster-operator/04A-Crd-kafkanodepool.yaml
- install/cluster-operator/060-Deployment-strimzi-cluster-operator.yaml
- install/drain-cleaner/README.md
- install/drain-cleaner/openshift/060-Deployment.yaml
- install/strimzi-admin/010-ClusterRole-strimzi-admin.yaml
- install/topic-operator/02-Role-strimzi-topic-operator.yaml
- install/topic-operator/04-Crd-kafkatopic.yaml
- install/topic-operator/05-Deployment-strimzi-topic-operator.yaml
- install/user-operator/02-Role-strimzi-user-operator.yaml
- install/user-operator/04-Crd-kafkauser.yaml
- install/user-operator/05-Deployment-strimzi-user-operator.yaml
Backport the Install files for 2.7
> Install files Backport for 2.7 release

- install/cluster-operator/020-ClusterRole-strimzi-cluster-operator-role.yaml
- install/cluster-operator/023-ClusterRole-strimzi-cluster-operator-role.yaml
- install/cluster-operator/031-ClusterRole-strimzi-entity-operator.yaml
- install/cluster-operator/040-Crd-kafka.yaml
- install/cluster-operator/041-Crd-kafkaconnect.yaml
- install/cluster-operator/042-Crd-strimzipodset.yaml
- install/cluster-operator/043-Crd-kafkatopic.yaml
- install/cluster-operator/044-Crd-kafkauser.yaml
- install/cluster-operator/045-Crd-kafkamirrormaker.yaml
- install/cluster-operator/046-Crd-kafkabridge.yaml
- install/cluster-operator/047-Crd-kafkaconnector.yaml
- install/cluster-operator/048-Crd-kafkamirrormaker2.yaml
- install/cluster-operator/049-Crd-kafkarebalance.yaml
- install/cluster-operator/04A-Crd-kafkanodepool.yaml
- install/cluster-operator/060-Deployment-strimzi-cluster-operator.yaml
- install/drain-cleaner/README.md
- install/drain-cleaner/openshift/060-Deployment.yaml
- install/strimzi-admin/010-ClusterRole-strimzi-admin.yaml
- install/topic-operator/02-Role-strimzi-topic-operator.yaml
- install/topic-operator/04-Crd-kafkatopic.yaml
- install/topic-operator/05-Deployment-strimzi-topic-operator.yaml
- install/user-operator/02-Role-strimzi-user-operator.yaml
- install/user-operator/04-Crd-kafkauser.yaml
- install/user-operator/05-Deployment-strimzi-user-operator.yaml
Backport install files for 2.7
> Backport install files for AMQ Streams 2.7

- operator-metadata/manifests/bundle.clusterserviceversion.yaml
Update bundle.clusterversion.yaml Docs with new Links
> Update bundle.clusterversion.yaml Docs with new Links

- proxy/image.yaml
> remove packages for testing

- operator-metadata/manifests/bundle.clusterserviceversion.yaml
> Update docs URL

- bridge/image.yaml
- bridge/modules/bridge/module.yaml
- drain-cleaner/image.yaml
- drain-cleaner/modules/drain-cleaner/module.yaml
- install/cluster-operator/060-Deployment-strimzi-cluster-operator.yaml
- install/drain-cleaner/openshift/060-Deployment.yaml
- install/topic-operator/05-Deployment-strimzi-topic-operator.yaml
- install/user-operator/05-Deployment-strimzi-user-operator.yaml
- kafka/kafka-3.4.0/image.yaml
- kafka/kafka-3.5.0/image.yaml
- kafka/modules/kafka/3.4.0/module.yaml
- kafka/modules/kafka/3.5.0/module.yaml
- kafka/modules/kafka/base/module.yaml
- operator-metadata/image.yaml
- operator-metadata/manifests/bundle.clusterserviceversion.yaml
- operator/image.yaml
- operator/modules/operator/module.yaml
Update image, module and install files for 2.5.2 release.
> Update for 2.5.2 release

- install/cluster-operator/060-Deployment-strimzi-cluster-operator.yaml
- kafka/modules/kafka/3.4.0/module.yaml
- kafka/modules/kafka/3.5.0/module.yaml
- kafka/modules/kafka/base/module.yaml
- operator/modules/operator/module.yaml
Fix typo and update MD5s for 2.5.2 CR2
> Fix typo and update MD5s for 2.5.2 CR2

- tools/report.sh
Updates the `report.sh` with the latest changes from upstream
> Backport latest changes to report.sh script

- bridge/modules/bridge/module.yaml
- kafka/modules/kafka/3.4.0/module.yaml
- kafka/modules/kafka/3.5.0/module.yaml
- kafka/modules/kafka/base/module.yaml
- operator/modules/operator/module.yaml
> Update md5s for 2.5.2 CR2

- operator-metadata/manifests/bundle.clusterserviceversion.yaml
- operator-metadata/manifests/kafkabridges.kafka.strimzi.io.crd.yaml
- operator-metadata/manifests/kafkaconnectors.kafka.strimzi.io.crd.yaml
- operator-metadata/manifests/kafkaconnects.kafka.strimzi.io.crd.yaml
- operator-metadata/manifests/kafkamirrormaker2s.kafka.strimzi.io.crd.yaml
- operator-metadata/manifests/kafkamirrormakers.kafka.strimzi.io.crd.yaml
- operator-metadata/manifests/kafkanodepools.kafka.strimzi.io.crd.yaml
- operator-metadata/manifests/kafkarebalances.kafka.strimzi.io.crd.yaml
- operator-metadata/manifests/kafkas.kafka.strimzi.io.crd.yaml
- operator-metadata/manifests/kafkatopics.kafka.strimzi.io.crd.yaml
- operator-metadata/manifests/kafkausers.kafka.strimzi.io.crd.yaml
- operator-metadata/manifests/strimzientityoperator.clusterrole.yaml
OLM Backport with `securityContext` field added for 2.8.0 release
> OLM Backport with securityContext field added for 2.8

- install/cluster-operator/060-Deployment-strimzi-cluster-operator.yaml
- operator-metadata/manifests/bundle.clusterserviceversion.yaml
Remove the `-` from the field.
> Fix typo in securityContext field

- kafka/modules/kafka/base/install.sh
This fixes latest Kafka build issues
> Adjust packagemanager in Kafka install scripts

- operator-metadata/image.yaml
- operator-metadata/metadata/annotations.yaml
Fixing OLM image and channel versions
> Fix bundle image descriptor file + annotations

- operator-metadata/manifests/bundle.clusterserviceversion.yaml
This reverts commit 454d178bcf76542338514d37cc3ff6e5afcabb32.
> Revert "[CPaaS] Update CSVs for AMQ Streams Bundle 2.8.0-0"

- operator-metadata/manifests/bundle.clusterserviceversion.yaml
Remove last 3 commits to fix revert error
> Revert "remove bot commit for force build"

- operator-metadata/automation/README.md
- operator-metadata/automation/tests/resources/new.format.internal.pull.specs.test.bundle.clusterserviceversion.yaml
- operator-metadata/automation/tests/test_bundle_automation.py
Writing proper unit tests for the `update_cluster_service_version_data` test created in this PR [1]
[1] https://github.com/jboss-container-images/amqstreams-1-openshift-image/pull/531
> Update Python unit tests for update_cluster_service_version_data function
